version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3.7.17

  speaker:
    build: ./speaker/.
    ports:
      - 8080
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  house:
    build: ./house/.
    ports:
      - 8080
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  member:
    build: ./member/.
    ports:
      - 8080
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MEMBER_NAME=Tom



